apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - dev-ns.yml

namespace: dev
#namePrefix: dev-
#nameSuffix: -dev

images:
  - name: bob2606/hello-http
    newTag: "latest"

labels:
  - pairs:
      env: dev
      rev: "0.1"
    includeSelectors: true

configMapGenerator:
  - name: hello-env
    envs:
      - hello.env

patches:
  - path: hello-env-cm-patch.yml
  - path: hello-volumes-patch.yml

replacements:
  - source:
      kind: ConfigMap
      name: hello-env
      fieldPath: data.PORT
    targets:
      - select:
          kind: Deployment
          name: hello
        fieldPaths:
          - spec.template.spec.containers.0.ports.0.containerPort
